### PR TITLE
PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
- This library in Web: http://platformio.ikravets.com/#!/lib/show/90/LPD8806
- Specification: [PlatformIO Library Manager](http://docs.platformio.ikravets.com/en/latest/librarymanager/index.html)
- Integration: [IDE Integration](http://docs.platformio.ikravets.com/en/latest/ide.html)

### CODE REVIEW

**Comment by ladyada** [comment]
closing since we found another solution!

**Comment by ivankravets** [comment]
😂

**Comment by ladyada** [comment]
@ivankravets thanks! we'll be closing some other old tickets so you may get notifications :)

**Comment by ivankravets** [comment]
See you soon on @PlatformIO side 😊

**Pull request closed without merging**
